import { PNU_ZONE_IDS } from "./pnuRoadZones.js";

export const PNU_ROAD_ZONE_FALLBACK_RULES = [
  {
    id: PNU_ZONE_IDS.MAIN_GATE,
    label: "부산대 정문 주요상권",
    roadName: "부산대학로",
    minBuildingNumber: 1,
    maxBuildingNumber: 80,
    variables: {
      LOCATION_LINE: "부산대 정문 주요상권",
      TRAFFIC_FEATURE_LINE: "대학가 보행 유동 입지",
      ACCESS_LINE: "부산대역·정문 접근 우수",
      RECOMMENDED_BUSINESS_LINE: "카페·분식·디저트 추천",
      CTA_LINE: "정문상권 임대문의",
    },
    recommendedBusinesses: ["카페", "분식", "디저트", "테이크아웃"],
  },
  {
    id: PNU_ZONE_IDS.MAIN_GATE,
    label: "부산대 정문 주요상권",
    roadName: "부산대학로63번길",
    minBuildingNumber: 1,
    maxBuildingNumber: 80,
    variables: {
      LOCATION_LINE: "부산대 정문 주요상권",
      TRAFFIC_FEATURE_LINE: "대학가 보행 유동 입지",
      ACCESS_LINE: "부산대역·정문 접근 우수",
      RECOMMENDED_BUSINESS_LINE: "카페·분식·디저트 추천",
      CTA_LINE: "정문상권 임대문의",
    },
    recommendedBusinesses: ["카페", "분식", "디저트", "테이크아웃"],
  },
  {
    id: PNU_ZONE_IDS.MAIN_GATE_ALLEY,
    label: "부산대 정문 골목상권",
    roadName: "부산대학로64번길",
    minBuildingNumber: 1,
    maxBuildingNumber: 100,
    variables: {
      LOCATION_LINE: "부산대 정문 골목상권",
      TRAFFIC_FEATURE_LINE: "대학가 보행 유동 입지",
      ACCESS_LINE: "부산대역·정문 접근 우수",
      RECOMMENDED_BUSINESS_LINE: "카페·분식·디저트 추천",
      CTA_LINE: "정문상권 임대문의",
    },
    recommendedBusinesses: ["카페", "분식", "디저트", "테이크아웃"],
  },
  {
    id: PNU_ZONE_IDS.STATION_CORE,
    label: "부산대역 핵심 활성화상권",
    roadName: "금정로68번길",
    minBuildingNumber: 1,
    maxBuildingNumber: 120,
    variables: {
      LOCATION_LINE: "부산대역 핵심상권",
      TRAFFIC_FEATURE_LINE: "역세권 유동 확보 입지",
      ACCESS_LINE: "부산대역 1·3번 출구권",
      RECOMMENDED_BUSINESS_LINE: "카페·팝업·디저트 추천",
      CTA_LINE: "역세권 임대문의",
    },
    recommendedBusinesses: ["카페", "팝업", "디저트", "테이크아웃"],
  },
  {
    id: PNU_ZONE_IDS.MAIN_GATE_ALLEY,
    label: "정문 골목형 혼합상권",
    roadName: "금정로60번길",
    minBuildingNumber: 1,
    maxBuildingNumber: 120,
    variables: {
      LOCATION_LINE: "정문 골목형 상권",
      TRAFFIC_FEATURE_LINE: "대학가 단골수요 입지",
      ACCESS_LINE: "정문·젊음의거리 인접",
      RECOMMENDED_BUSINESS_LINE: "카페·서점·소형샵 추천",
      CTA_LINE: "골목상권 임대문의",
    },
    recommendedBusinesses: ["카페", "서점", "소형샵", "디저트"],
  },
  {
    id: PNU_ZONE_IDS.STATION_CORE,
    label: "부산대역·정문 연결상권",
    roadName: "금강로",
    minBuildingNumber: 230,
    maxBuildingNumber: 285,
    variables: {
      LOCATION_LINE: "부산대역 인접상권",
      TRAFFIC_FEATURE_LINE: "역세권 유동 확보 입지",
      ACCESS_LINE: "부산대역·정문 접근 우수",
      RECOMMENDED_BUSINESS_LINE: "카페·분식·간편식 추천",
      CTA_LINE: "역세권 임대문의",
    },
    recommendedBusinesses: ["카페", "분식", "간편식", "테이크아웃"],
  },
  {
    id: PNU_ZONE_IDS.STATION_CORE,
    label: "부산대역 핵심 활성화상권",
    roadName: "금정로",
    minBuildingNumber: 1,
    maxBuildingNumber: 120,
    variables: {
      LOCATION_LINE: "부산대역 핵심상권",
      TRAFFIC_FEATURE_LINE: "역세권 유동 확보 입지",
      ACCESS_LINE: "부산대역·정문 접근 우수",
      RECOMMENDED_BUSINESS_LINE: "카페·팝업·디저트 추천",
      CTA_LINE: "역세권 임대문의",
    },
    recommendedBusinesses: ["카페", "팝업", "디저트", "테이크아웃"],
  },
  {
    id: PNU_ZONE_IDS.NORTH_GATE_FOOD,
    label: "부산대 북문 밥집상권",
    roadName: "금강로",
    minBuildingNumber: 300,
    maxBuildingNumber: 360,
    variables: {
      LOCATION_LINE: "부산대 북문 밥집상권",
      TRAFFIC_FEATURE_LINE: "학생 식사수요 입지",
      ACCESS_LINE: "북문·원룸촌 접근 우수",
      RECOMMENDED_BUSINESS_LINE: "백반·분식·덮밥 추천",
      CTA_LINE: "북문상권 임대문의",
    },
    recommendedBusinesses: ["백반", "분식", "덮밥", "도시락"],
  },
  {
    id: PNU_ZONE_IDS.NORTH_GATE_FOOD,
    label: "북문·북맛골 식사상권",
    roadName: "수림로",
    minBuildingNumber: 1,
    maxBuildingNumber: 160,
    variables: {
      LOCATION_LINE: "부산대 북문 밥집상권",
      TRAFFIC_FEATURE_LINE: "학생 식사수요 입지",
      ACCESS_LINE: "북문·원룸촌 접근 우수",
      RECOMMENDED_BUSINESS_LINE: "백반·분식·덮밥 추천",
      CTA_LINE: "북문상권 임대문의",
    },
    recommendedBusinesses: ["백반", "분식", "덮밥", "도시락"],
  },
  {
    id: PNU_ZONE_IDS.NORTH_GATE_FOOD,
    label: "북문·북맛골 식사상권",
    roadName: "수림로85번길",
    minBuildingNumber: 1,
    maxBuildingNumber: 120,
    variables: {
      LOCATION_LINE: "부산대 북문 밥집상권",
      TRAFFIC_FEATURE_LINE: "학생 식사수요 입지",
      ACCESS_LINE: "북문·원룸촌 접근 우수",
      RECOMMENDED_BUSINESS_LINE: "백반·분식·덮밥 추천",
      CTA_LINE: "북문상권 임대문의",
    },
    recommendedBusinesses: ["백반", "분식", "덮밥", "도시락"],
  },
  {
    id: PNU_ZONE_IDS.NORTH_GATE_FOOD,
    label: "북문·북맛골 식사상권",
    roadName: "금강로321번길",
    minBuildingNumber: 1,
    maxBuildingNumber: 120,
    variables: {
      LOCATION_LINE: "부산대 북문 밥집상권",
      TRAFFIC_FEATURE_LINE: "학생 식사수요 입지",
      ACCESS_LINE: "북문·원룸촌 접근 우수",
      RECOMMENDED_BUSINESS_LINE: "백반·분식·덮밥 추천",
      CTA_LINE: "북문상권 임대문의",
    },
    recommendedBusinesses: ["백반", "분식", "덮밥", "도시락"],
  },
  {
    id: PNU_ZONE_IDS.YOUTH_CULTURE_STREET,
    label: "부산대 젊음의거리",
    roadName: "장전온천천로",
    minBuildingNumber: 1,
    maxBuildingNumber: 120,
    variables: {
      LOCATION_LINE: "부산대 젊음의거리",
      TRAFFIC_FEATURE_LINE: "청년 문화골목 입지",
      ACCESS_LINE: "부산대역 도보권 상권",
      RECOMMENDED_BUSINESS_LINE: "카페·소품샵·공방 추천",
      CTA_LINE: "감성상권 임대문의",
    },
    recommendedBusinesses: ["카페", "소품샵", "공방", "디저트"],
  },
  {
    id: PNU_ZONE_IDS.JANGJEON_STATION_NORTH,
    label: "장전역 북문 접근상권",
    roadName: "장전온천천로",
    minBuildingNumber: 121,
    maxBuildingNumber: 240,
    variables: {
      LOCATION_LINE: "장전역 북문상권",
      TRAFFIC_FEATURE_LINE: "통학·생활수요 입지",
      ACCESS_LINE: "장전역·북문 접근 편리",
      RECOMMENDED_BUSINESS_LINE: "커피·도시락·서비스 추천",
      CTA_LINE: "생활상권 임대문의",
    },
    recommendedBusinesses: ["커피", "도시락", "생활서비스", "간편식"],
  },
  {
    id: PNU_ZONE_IDS.JANGJEON_STATION_NORTH,
    label: "장전역 북문 접근상권",
    roadName: "금강로",
    minBuildingNumber: 361,
    maxBuildingNumber: 430,
    variables: {
      LOCATION_LINE: "장전역 북문상권",
      TRAFFIC_FEATURE_LINE: "통학·생활수요 입지",
      ACCESS_LINE: "장전역·북문 접근 편리",
      RECOMMENDED_BUSINESS_LINE: "커피·도시락·서비스 추천",
      CTA_LINE: "생활상권 임대문의",
    },
    recommendedBusinesses: ["커피", "도시락", "생활서비스", "간편식"],
  },
  {
    id: PNU_ZONE_IDS.BACK_GATE_JANGJEON_RO,
    label: "부산대 후문 생활상권",
    roadName: "장전로",
    minBuildingNumber: 1,
    maxBuildingNumber: 160,
    variables: {
      LOCATION_LINE: "부산대 후문 생활상권",
      TRAFFIC_FEATURE_LINE: "장전로 생활 유동 입지",
      ACCESS_LINE: "후문·버스정류장 인접",
      RECOMMENDED_BUSINESS_LINE: "커피·간편식·서비스 추천",
      CTA_LINE: "후문상권 임대문의",
    },
    recommendedBusinesses: ["커피", "간편식", "생활서비스", "미용"],
  },
];
