export const PNU_ROAD_ZONE_FALLBACK_RULES = [
  {
    id: "pnu_main_gate",
    label: "부산대 정문 주요상권",
    roadName: "부산대학로",
    minBuildingNumber: 1,
    maxBuildingNumber: 80,
    variables: {
      LOCATION_LINE: "부산대 정문 주요상권",
      TRAFFIC_FEATURE_LINE: "대학가 보행 유동 입지",
      ACCESS_LINE: "부산대역·정문 접근 우수",
      RECOMMENDED_BUSINESS_LINE: "카페·분식·디저트 추천",
      CTA_LINE: "정문상권 임대문의",
    },
    recommendedBusinesses: ["카페", "분식", "디저트", "테이크아웃"],
  },
  {
    id: "pnu_main_gate_alley",
    label: "부산대 정문 골목상권",
    roadName: "부산대학로64번길",
    minBuildingNumber: 1,
    maxBuildingNumber: 80,
    variables: {
      LOCATION_LINE: "부산대 정문 골목상권",
      TRAFFIC_FEATURE_LINE: "대학가 보행 유동 입지",
      ACCESS_LINE: "부산대역·정문 접근 우수",
      RECOMMENDED_BUSINESS_LINE: "카페·분식·디저트 추천",
      CTA_LINE: "정문상권 임대문의",
    },
    recommendedBusinesses: ["카페", "분식", "디저트", "테이크아웃"],
  },
  {
    id: "pnu_station_main",
    label: "부산대역·정문 연결상권",
    roadName: "금강로",
    minBuildingNumber: 230,
    maxBuildingNumber: 285,
    variables: {
      LOCATION_LINE: "부산대역 인접상권",
      TRAFFIC_FEATURE_LINE: "역세권 유동 확보 입지",
      ACCESS_LINE: "부산대역·정문 접근 우수",
      RECOMMENDED_BUSINESS_LINE: "카페·분식·간편식 추천",
      CTA_LINE: "역세권 임대문의",
    },
    recommendedBusinesses: ["카페", "분식", "간편식", "테이크아웃"],
  },
  {
    id: "pnu_north_gate",
    label: "부산대 북문 생활상권",
    roadName: "금강로",
    minBuildingNumber: 300,
    maxBuildingNumber: 360,
    variables: {
      LOCATION_LINE: "부산대 북문 생활상권",
      TRAFFIC_FEATURE_LINE: "학생 식사수요 입지",
      ACCESS_LINE: "북문·원룸촌 접근 우수",
      RECOMMENDED_BUSINESS_LINE: "백반·분식·덮밥 추천",
      CTA_LINE: "북문상권 임대문의",
    },
    recommendedBusinesses: ["백반", "분식", "덮밥", "도시락"],
  },
  {
    id: "pnu_jangjeonro_back_gate",
    label: "부산대 후문 생활상권",
    roadName: "장전로",
    minBuildingNumber: 1,
    maxBuildingNumber: 120,
    variables: {
      LOCATION_LINE: "부산대 후문 생활상권",
      TRAFFIC_FEATURE_LINE: "장전로 생활 유동 입지",
      ACCESS_LINE: "후문·버스정류장 인접",
      RECOMMENDED_BUSINESS_LINE: "커피·간편식·서비스 추천",
      CTA_LINE: "후문상권 임대문의",
    },
    recommendedBusinesses: ["커피", "간편식", "생활서비스", "미용"],
  },
];
