export const PNU_ROAD_ZONES = [
  {
    id: "pnu_station_core",
    label: "부산대역 핵심 활성화상권",
    shortLabel: "부산대역 핵심상권",
    center: { lat: 35.2299, lng: 129.0881 },
    radiusMeters: 360,
    priority: 10,
    keywords: ["부산대역", "금정로68번길", "1번 출구", "3번 출구", "역세권"],
    locationLine: "부산대역 핵심상권",
    trafficFeatureLine: "역세권 유동 확보 입지",
    accessLine: "부산대역 1·3번 출구권",
    recommendedBusinesses: ["카페", "팝업", "디저트"],
    ctaLine: "핵심상권 임대문의",
    customerGroups: ["부산대 학생", "20대 방문객", "역 이용객", "외부 방문객"],
    salesPotential: "역세권 유동 기반 수요 기대",
    deliveryFit: "중",
  },
  {
    id: "main_gate",
    label: "정문 메인상권",
    shortLabel: "부산대 정문 주요상권",
    center: { lat: 35.2316, lng: 129.084 },
    radiusMeters: 330,
    priority: 9,
    keywords: ["정문", "부산대 정문", "대학로", "금정로"],
    locationLine: "부산대 정문 주요상권",
    trafficFeatureLine: "대학가 보행 유동 입지",
    accessLine: "부산대역·정문 접근 우수",
    recommendedBusinesses: ["카페", "분식", "디저트"],
    ctaLine: "정문상권 임대문의",
    customerGroups: ["부산대 학생", "교직원", "방문객", "약속 수요"],
    salesPotential: "보행 유동과 접근성 기반 수요 기대",
    deliveryFit: "중",
  },
  {
    id: "youth_culture_street",
    label: "젊음의거리 문화상권",
    shortLabel: "부산대 젊음의거리",
    center: { lat: 35.2307, lng: 129.0861 },
    radiusMeters: 300,
    priority: 8,
    keywords: ["젊음의거리", "장전온천천로", "문화골목", "청년"],
    locationLine: "부산대 젊음의거리",
    trafficFeatureLine: "청년 문화골목 입지",
    accessLine: "부산대역 도보권 상권",
    recommendedBusinesses: ["카페", "소품샵", "공방"],
    ctaLine: "감성상권 임대문의",
    customerGroups: ["10~20대", "데이트·약속 수요", "쇼핑·카페 방문객"],
    salesPotential: "감성 소비와 체류 수요 기대",
    deliveryFit: "중",
  },
  {
    id: "main_gate_alley",
    label: "정문 골목형 혼합상권",
    shortLabel: "정문 골목형 상권",
    center: { lat: 35.2311, lng: 129.0851 },
    radiusMeters: 280,
    priority: 7,
    keywords: ["금정로60번길", "금정로68번길", "골목", "소형창업"],
    locationLine: "정문 골목형 상권",
    trafficFeatureLine: "대학가 단골수요 입지",
    accessLine: "정문·젊음의거리 인접",
    recommendedBusinesses: ["카페", "서점", "소형샵"],
    ctaLine: "골목상권 임대문의",
    customerGroups: ["학생", "단골 방문객", "인근 거주민"],
    salesPotential: "소형창업과 단골 방문 수요 기대",
    deliveryFit: "중하",
  },
  {
    id: "north_gate_food",
    label: "북문·북맛골 식사상권",
    shortLabel: "부산대 북문 밥집상권",
    center: { lat: 35.236, lng: 129.0805 },
    radiusMeters: 390,
    priority: 9,
    keywords: ["북문", "북맛골", "수림로", "수림로85번길", "금강로321번길"],
    locationLine: "부산대 북문 밥집상권",
    trafficFeatureLine: "학생 식사수요 입지",
    accessLine: "북문·원룸촌 접근 우수",
    recommendedBusinesses: ["백반", "분식", "덮밥"],
    ctaLine: "북문상권 임대문의",
    customerGroups: ["학생", "자취생", "교직원", "북문 인근 거주자"],
    salesPotential: "학생 식사수요 기반 반복 방문 기대",
    deliveryFit: "높음",
  },
  {
    id: "jangjeon_station_north",
    label: "장전역 북문 접근상권",
    shortLabel: "장전역 북문상권",
    center: { lat: 35.2382, lng: 129.0871 },
    radiusMeters: 430,
    priority: 8,
    keywords: ["장전역", "상남국제관", "북문 접근", "통학"],
    locationLine: "장전역 북문상권",
    trafficFeatureLine: "통학·생활수요 입지",
    accessLine: "장전역·북문 접근 편리",
    recommendedBusinesses: ["커피", "도시락", "서비스"],
    ctaLine: "생활상권 임대문의",
    customerGroups: ["북문 방면 학생", "교직원", "장전역 이용객"],
    salesPotential: "통학동선과 생활동선 기반 수요 기대",
    deliveryFit: "중",
  },
  {
    id: "back_gate_jangjeon_ro",
    label: "후문·장전로 생활상권",
    shortLabel: "부산대 후문 생활상권",
    center: { lat: 35.2354, lng: 129.0839 },
    radiusMeters: 350,
    priority: 7,
    keywords: ["후문", "장전로", "부산대학교후문", "버스정류장"],
    locationLine: "부산대 후문 생활상권",
    trafficFeatureLine: "장전로 생활 유동 입지",
    accessLine: "후문·버스정류장 인접",
    recommendedBusinesses: ["커피", "간편식", "서비스"],
    ctaLine: "후문상권 임대문의",
    customerGroups: ["학생", "원룸 거주자", "버스 이용객", "인근 주민"],
    salesPotential: "생활동선·주거수요 기반 안정 수요 기대",
    deliveryFit: "중상",
  },
  {
    id: "campus_aux_gate",
    label: "문창쪽문·남문·구정문 보조 출입상권",
    shortLabel: "부산대 캠퍼스 인접",
    center: { lat: 35.2327, lng: 129.0812 },
    radiusMeters: 360,
    priority: 6,
    keywords: ["문창쪽문", "남문", "구정문", "쪽문", "캠퍼스"],
    locationLine: "부산대 캠퍼스 인접",
    trafficFeatureLine: "학생 생활수요 입지",
    accessLine: "학내 출입동선 인접",
    recommendedBusinesses: ["커피", "도시락", "문구"],
    ctaLine: "캠퍼스상권 임대문의",
    customerGroups: ["특정 단과대 학생", "교직원", "내부 이동객"],
    salesPotential: "특정 학내 수요 기반 소형 업종 적합",
    deliveryFit: "중하",
  },
];

export const PNU_MAX_ANALYSIS_RADIUS_METERS = 1400;
